//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeachersPet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeachersPet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #!/usr/bin/perl
        ///#
        ///# Please read all the comments down to the line that says &quot;TOP&quot;.
        ///# These comments are divided into three sections:
        ///#
        ///#     1. usage instructions
        ///#     2. installation instructions
        ///#     3. standard copyright
        ///#
        ///# Feel free to share this script with other instructors of programming
        ///# classes, but please do not place the script in a publicly accessible
        ///# place.  Comments, questions, and bug reports should be sent to
        ///# moss-request@moss.stanford.edu.
        ///#
        ///# IMPORTANT: This script is known to work [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MossPerlScript {
            get {
                return ResourceManager.GetString("MossPerlScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include &lt;iostream&gt;
        ///#include &lt;vector&gt;
        ///#include &lt;fstream&gt;
        ///#include &lt;unistd.h&gt;
        ///using namespace std;
        ///
        ///struct Image
        ///{
        ///    struct Header
        ///    {
        ///        char idLength;
        ///        char colorMapType;
        ///        char dataTypeCode;
        ///        short colorMapOrigin;
        ///        short colorMapLength;
        ///        char colorMapDepth;
        ///        short xOrigin;
        ///        short yOrigin;
        ///        short width = 0;
        ///        short height = 0;
        ///        char bitsPerPixel;
        ///        char imageDescriptor;
        ///        
        ///        Header();
        ///        // Read all of the h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string P2Grader {
            get {
                return ResourceManager.GetString("P2Grader", resourceCulture);
            }
        }
    }
}
